services:
  sammelkarten:
    build: .
    container_name: sammelkarten
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - web
    labels:
      caddy: sammelkarten.hackerwerkstatt.de
      caddy.reverse_proxy: "{{upstreams 5000}}"

networks:
  web:
    external: true
